### PR TITLE
Adds nth operator (closes #51)

### LINKED ISSUE #51: Other ordinals than First and Last
Cf. https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/issues/95#issuecomment-72521874

I don't see any way to describe a question such as "Who is the fourth president of the United States?" with the current datamodel.

We should add an operator for this.

Two alternatives:

* `Nth(l,n)` returns the `n`-th element of the list `l`.
* `Minus(l1,l2)` returns the list containing the elements of `l1` which are not in `l2`.

We have `Nth(l,4) = First(Minus(Minus(Minus(l,First(l)),First(l)),First(l)))`.

### PR DESCRIPTION
**Pull request by Tpt**

### CODE REVIEW

**Comment by Ezibenroc** [comment]
> (the first element of the list is at position 1). If *i < 0* then it returns the *i*th element from the end (*nth(-1, l)* returns the last element of the list).

Would be better to begin indexing at 0 (this is almost a standard in CS). Especially if -1 is the last element.
Would be great to allow other negatives than -1.

**Comment by Tpt** [comment]
> Would be better to begin indexing at 0

Yes, make sense

> Would be great to allow other negatives than -1.

It's what is done: "If *i < 0* then it returns the *i*th element from the end"

**Comment by Ezibenroc** [comment]
> It's what is done: "If i < 0 then it returns the ith element from the end"

Sorry, read too fast.

Ok for me.

**Comment by rcharron** [comment]
Would be better to begin indexing at 0 (this is almost a standard in CS) => So be carefull when parsing, because in natural language, indexing start at 1

**Comment by Tpt** [comment]
Let's go with it!

**Pull request merged**
