### PR TITLE
Adds the inverse abstract operator and the inverse-predicate attribute to triples

### LINKED ISSUE #52: Reverse predicates
Following the discussion we had here: https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/pull/106

There is an issue about the predicates, well illustrated by the following example:
* Where does the animal live? -> `(animal,residence,?)` or `(?,inhabitant,animal)`
* Who lives in the farm? -> `(?,residence,farm)` or `(farm,inhabitant,?)`

All these triples are correct. But some of them might fail very often on some databases (e.g. Wikidata).

An arbitrary choice from the question parsing modules would be a poor choice, we need to modify the datamodel.

---------------

**Proposition 1**

A triple with hole is `[X,N1,N2]` that returns the set of values V such that `(X,N1,V)` is a correct full triple, or `(V,N2,X)` is a correct full triple.

Examples:

Where does the animal live? -> `[animal,residence,inhabitant]`
Who lives in the farm? -> `[farm,inhabitant,residence]`

**Proposition 2**

Use `(X, N1, ?) ∪ (?, N2, X)` (do not change the datamodel).

**Proposition 3**

`[X, B1, B2] = { c | ∃ a ∈ X ∃ b ∈ B1 (a, b, c) } ∪ { a | ∃ c ∈ X ∃ b ∈ B2 (a, b, c) }`

**Proposition 4**
`(X, B1 ∪ reverse(B2), ?)` such that `(X, B1 ∪ reverse(B2), ?) = (?, B2 ∪ reverse(B1), X)`
(we simply add a field in the `Triple` implementation)

### PR DESCRIPTION
**Pull request by Tpt**
Does not add any additional power to the DataModel but allows to significantly reduce the tree size.

The name "inverse" is taken from the owl:inverseOf property of OWL.

Closes #52

### CODE REVIEW

**Comment by ProgVal** [comment]
Is `inverse-predicate` mandatory?

**Comment by Tpt** [comment]
No, I've just updated the PR to reflect this.

**Comment by Ezibenroc** [comment]
We should not consider the `inverse-predicate` as optional: it has exactly the same importance as the `predicate`.

**Comment by yhamoudi** [comment]
> We should not consider the inverse-predicate as optional: it has exactly the same importance as the predicate.

+1 But how can we do if there is no inverse predicate ?

**Comment by Ezibenroc** [comment]
> +1 But how can we do if there is no inverse predicate ?

And if there is no predicate? (this can also happen)

→We allow empty-lists for predicate or reverse-predicate.

**Comment by yhamoudi** [comment]
> And if there is no predicate? (this can also happen)

We could reverse the triple (the inverse predicate becomes the predicate), but it would be better to avoid this (otherwise people may think that `predicate` is enough and `inverse-predicate` is totally optional).

**Comment by yhamoudi** [comment]
Can we add the following text at the end of https://github.com/ProjetPP/Documentation/blob/revers/data-model.md#triple ?

Please note that the previous triple is equivalent to:
```
{
    "type": "triple",
    "subject": {"type": "missing"},
    "predicate": {"type": "resource", "value": "inhabitant"},
    "inverse-predicate": {"type": "resource", "value": "residence"},
    "object": {"type": "resource", "value": "Barack Obama"}
}
```

**Comment by Tpt** [comment]
My own thought is that inverse predicate is a hack done in order to reduce the query tree size when we build them using nounification technique. So, yes, when they are present, they are as "important" as regular predicates but I don't see why it is a reason to make this parameter mandatory as it'll have often an empty value. For example, if I write requests by hand, I don't think I'll often use reverse predicates.

More, I think that simple modules (like OEIS) should be able to answer to most of questions without having to deal with inverse predicates that is more an "advanced feature" for big modules like the Wikidata one.

With the risk of repeating myself: the data model is not only there to be a nice output of NLP-grammatical but is a shared languages for our platform modules and so we shouldn't make there life harder only to simplify the job of NLP-grammatical.

--------

> Can we add the following text at the end of https://github.com/ProjetPP/Documentation/blob/revers/data-model.md#triple ?

Yes. But we should maybe add a paragraph after the definition of *inverse* to give an example of use and explain this equality that is, I think, more readable when explained with the abstract notation than with the serialization.

**Comment by ProgVal** [comment]
:+1: @Tpt

**Comment by yhamoudi** [comment]
> With the risk of repeating myself: the data model is not only there to be a nice output of NLP-grammatical but is a shared languages for our platform modules and so we shouldn't make there life harder only to simplify the job of NLP-grammatical.

If doesn't change anything for the question parsing (we always have something to put into `predicate`). See https://github.com/ProjetPP/PPP-QuestionParsing-Grammatical/pull/106#issuecomment-73723785 for the reasons why i think we shouldn't depict `inverse-predicate` as optional.

But leave it at it is (optional), developers will just have to be aware of the importance of `inverse-predicate`.

(for me, you can merge :+1:)

**Comment by Ezibenroc** [comment]
> But leave it at it is (optional), developers will just have to be aware of the importance of inverse-predicate.

This does not make sense: if the inverse-predicate is important then it should not be optionnal.

**Comment by yhamoudi** [comment]
> This does not make sense: if the inverse-predicate is important then it should not be optionnal.

We could consider that it is optional because sometimes it doesn't exist, not because it is less useful than `predicate`.

**Comment by Ezibenroc** [comment]
Alright.

**Comment by Tpt** [comment]
@s-i-newton Do you have any concerns about this addition to the data model?

**Comment by yhamoudi** [comment]
Silence is consent. I think we can merge now...

**Comment by ProgVal** [comment]
I think @s-i-newton just has no Internet connection.

**Comment by yhamoudi** [comment]
How did he registred on the forum?

**Comment by ProgVal** [comment]
Hmm, indeed

**Pull request merged**
